version: "3.9"

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - target: 80
        published: 80

      - target: 443
        published: 443
    networks:
      - proxy
      - proxy_platform_overlay
    volumes:
      - certificates:/etc/letsencrypt
      - npm:/data
    configs:
      - source: npm_hsts
        target: /app/templates/_hsts.conf
    deploy:
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME_PROXY}
      replicas: 1

networks:
  proxy:
    external: true
  proxy_platform_overlay:
    external: true

volumes:
  certificates:
    external: true
  npm:

configs:
  npm_hsts:
    external: true